name: Deploy Infrastructure

on:
  # push:
  #   branches:
  #     - master
    pull_request:
    branches:
      - master

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
#      uses: hashicorp/terraform-github-actions/init@v0.4.0
#      uses: hashicorp/terraform-github-actions/init@v1
      run: terraform init
      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        TF_ACTION_WORKING_DIR: 'gh-actions:'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Validate
#      uses: hashicorp/terraform-github-actions/validate@v0.3.7
      id: validate
      run: terraform validate -no-color

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@master
    #   with:
    #     role-to-assume: arn:aws:iam::258372532888:role/gitgub-actions-terraform
    #     aws-region: us-east-1
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Apply
      # uses: hashicorp/terraform-github-actions/apply@v0.4.0
      id: apply
      run: terraform apply -auto-approve
      env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # profile: globery
        # region: us-east-1


# defaults:
#   run:
# #    working-directory: ${{ env.tf_actions_working_dir }}
# permissions:
#   pull-requests: write
#   push: write 
# steps:
# - uses: actions/checkout@v3
# - uses: hashicorp/setup-terraform@v2

# - name: Terraform fmt
#   id: fmt
#   run: terraform fmt -check
#   continue-on-error: true

# - name: Terraform Init
#   id: init
#   run: terraform init

# - name: Terraform Validate
#   id: validate
#   run: terraform validate -no-color

# - name: Terraform Plan
#   id: plan
#   run: terraform plan -no-color
#   continue-on-error: true